### ISSUE TITLE
Doesn't compile using erlang.mk

### ISSUE THREAD

**Issue by jordanchaitin** [SpaceTime-IoT/pgo#3]
The app seems to need an endless list of dependencies. I've had to download a very large number of dependencies manually, well over 200 MB so far, and it is still complaining about missing more. Did this app really need to be so heavy, especially with Prometheus - maybe a bit ironic that one cannot use a Erlang package with getting Golang and over a dozen of Go packages. 

It seems I'm missing something painfully obvious and that there is a more straightforward way of getting it to compile using erlang.mk?

**Comment by yogesch** [comment]
The cause of the problem was using an outdated version of the rebar.lock file to manually include dependencies. The rebar.lock file has now been updated in the master branch, and Prometheus is no longer a dependency. The app works fine now.
